'use client';

import React, { useEffect, useState } from 'react';
import { Award, Eye, EyeOff, LoaderCircle, Play, RefreshCw, Save, Search, ShieldAlert, Trophy } from 'lucide-react';

async function request(url, options) { const response = await fetch(url, options); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Не удалось выполнить действие.'); return data; }
function size(value) { return value < 1024 ? `${value} Б` : value < 1048576 ? `${Math.ceil(value / 1024)} КБ` : `${(value / 1048576).toFixed(1)} МБ`; }

export default function AdminLevels({ onNotice }) {
  const [data, setData] = useState(null);
  const [q, setQ] = useState('');
  const [busy, setBusy] = useState(false);
  const load = async (query = q) => { try { setData(await request(`/api/admin/levels?q=${encodeURIComponent(query)}`)); } catch (error) { onNotice(error.message, 'error'); } };
  useEffect(() => { load(''); }, []);
  const act = async (payload, message = 'Готово.') => { setBusy(true); try { await request('/api/admin/levels', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); await load(); onNotice(message); } catch (error) { onNotice(error.message, 'error'); } finally { setBusy(false); } };
  const saveConfig = async () => { setBusy(true); try { const result = await request('/api/admin/levels', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ config: data.config }) }); setData((current) => ({ ...current, config: result.config })); onNotice('Настройки XP и рангов сохранены. Для существующих читателей запустите безопасный пересчёт.'); } catch (error) { onNotice(error.message, 'error'); } finally { setBusy(false); } };
  const backfill = async () => {
    if (!window.confirm(`Пересчитать ${data.preview.readers} читателей пакетами по 25? Операцию можно остановить между пакетами.`)) return;
    setBusy(true); let cursor = ''; let processed = 0;
    try {
      do { const result = await request('/api/admin/levels', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action: 'backfill', cursor, batchSize: 25 }) }); processed += result.processed; cursor = result.nextCursor || ''; onNotice(`Пересчитано: ${processed}.`); } while (cursor);
      await load(); onNotice(`Пересчёт завершён: ${processed} читателей.`);
    } catch (error) { onNotice(`${error.message} Уже обработано: ${processed}. Повторный запуск безопасен.`, 'error'); } finally { setBusy(false); }
  };
  if (!data) return <section className="admin-content admin-levels"><div className="admin-levels-loading"><LoaderCircle className="spin" /> Загружаем систему уровней…</div></section>;
  const setXp = (key, value) => setData((current) => ({ ...current, config: { ...current.config, xp: { ...current.config.xp, [key]: Number(value) } } }));
  const setRank = (index, patch) => setData((current) => ({ ...current, config: { ...current.config, ranks: current.config.ranks.map((item,i) => i === index ? { ...item, ...patch } : item) } }));
  return <section className="admin-content admin-levels">
    <div className="admin-levels-head"><div><span className="admin-kicker">МАСТЕРА BOOKNERD</span><h1>Уровни<br /><em>и рейтинг.</em></h1><p>Компактная статистика без записи каждого движения по странице.</p></div><a href="/ranking" target="_blank" rel="noreferrer"><Eye size={17} /> Предпросмотр рейтинга</a></div>
    <div className="admin-level-overview"><article><Trophy /><strong>{data.preview.readers}</strong><span>читателей для пересчёта</span></article><article><Award /><strong>{data.preview.estimatedNewRows}</strong><span>примерно новых строк</span></article><article><ShieldAlert /><strong>{size(data.preview.estimatedBytes)}</strong><span>прогноз роста D1</span></article><article><ShieldAlert /><strong>{data.flagged.length}</strong><span>требуют проверки</span></article></div>
    <section className="admin-level-card"><div><h2>Безопасный пересчёт</h2><p>{data.preview.note} Повторный запуск не удваивает XP.</p></div><button type="button" onClick={backfill} disabled={busy}><Play size={17} /> {busy ? 'Идёт пересчёт…' : 'Запустить после проверки'}</button></section>
    <section className="admin-level-card admin-xp-config"><div><h2>Опыт за действия</h2><p>Сервер рассчитывает XP сам. Клиент не может передать количество опыта.</p></div><div>{[['chapter','Уникальная глава'],['book','Завершённая книга'],['series','Завершённая серия'],['review','Содержательный отзыв'],['confirmedError','Подтверждённая ошибка'],['threeReadingDays','Три даты за неделю'],['groupRead','Совместное чтение']].map(([key,label]) => <label key={key}><span>{label}</span><input type="number" min="0" value={data.config.xp[key]} onChange={(event) => setXp(key,event.target.value)} /></label>)}</div><div className="admin-level-curve"><label><span>База формулы</span><input type="number" value={data.config.levelCurve.base} onChange={(event) => setData((current) => ({ ...current, config: { ...current.config, levelCurve: { ...current.config.levelCurve, base: Number(event.target.value) } } }))} /></label><label><span>Рост формулы</span><input type="number" value={data.config.levelCurve.growth} onChange={(event) => setData((current) => ({ ...current, config: { ...current.config, levelCurve: { ...current.config.levelCurve, growth: Number(event.target.value) } } }))} /></label><label><span>Карточек номинаций на главной</span><input type="number" min="1" max="5" value={data.config.homeCardCount} onChange={(event) => setData((current) => ({ ...current, config: { ...current.config, homeCardCount: Number(event.target.value) } }))} /></label></div><button type="button" onClick={saveConfig} disabled={busy}><Save size={17} /> Сохранить настройки</button></section>
    <section className="admin-level-card"><div><h2>Ранги и границы</h2><p>Название, начальный уровень и цвет декоративной рамки можно менять.</p></div><div className="admin-rank-config">{data.config.ranks.map((rank,index) => <label key={rank.key}><span>{rank.icon} {rank.key}</span><input value={rank.name} onChange={(event) => setRank(index,{ name:event.target.value })} /><input type="number" min="1" value={rank.minLevel} onChange={(event) => setRank(index,{ minLevel:Number(event.target.value) })} aria-label={`Минимальный уровень ранга ${rank.name}`} /><input type="color" value={rank.frameColor} onChange={(event) => setRank(index,{ frameColor:event.target.value })} aria-label={`Цвет рамки ранга ${rank.name}`} /></label>)}</div></section>
    <section className="admin-level-card"><div><h2>Номинации</h2><p>Отключённые номинации не присуждаются при следующем завершении месяца.</p></div><div className="admin-nomination-config">{data.config.nominations.map((nomination,index) => <label key={nomination.key}><span><strong>{nomination.name}</strong><small>{nomination.key}</small></span><input type="checkbox" checked={nomination.enabled !== false} onChange={(event) => setData((current) => ({ ...current, config: { ...current.config, nominations: current.config.nominations.map((item,i) => i === index ? { ...item, enabled:event.target.checked } : item) } }))} aria-label={`Включить номинацию ${nomination.name}`} /></label>)}</div></section>
    <section className="admin-level-card"><div className="admin-reader-search"><div><h2>Читатели и проверка</h2><p>Изменения XP сохраняют владельца, время, старое и новое значение и причину.</p></div><form onSubmit={(event) => { event.preventDefault(); load(q); }}><input value={q} onChange={(event) => setQ(event.target.value)} placeholder="Имя или публичный ID" /><button aria-label="Найти читателя"><Search size={17} /></button></form></div><div className="admin-level-readers">{data.readers.map((reader) => <article key={reader.public_id}><span><strong>{reader.display_name || 'Читатель BOOKNERD'}</strong><small>Уровень {reader.level} · {reader.total_xp} XP · {reader.completed_books} книг · {reader.completed_chapters} глав · {reader.public_id}</small>{reader.suspicious_reason ? <em>{reader.suspicious_reason}</em> : null}</span><button type="button" onClick={() => act({ action:'recalculate', publicId:reader.public_id },'Читатель пересчитан.')} disabled={busy} aria-label="Пересчитать"><RefreshCw size={15} /></button><button type="button" onClick={() => act({ action:'rating-status', publicId:reader.public_id, status:reader.rating_status === 'active' ? 'review' : 'active' },reader.rating_status === 'active' ? 'Читатель временно исключён из рейтинга.' : 'Читатель возвращён в рейтинг.')} disabled={busy} aria-label={reader.rating_status === 'active' ? 'Исключить из рейтинга' : 'Вернуть в рейтинг'}><ShieldAlert size={15} /></button><button type="button" onClick={() => act({ action:'public-visible', publicId:reader.public_id, visible:!reader.public_visible },reader.public_visible ? 'Профиль скрыт с главной.' : 'Профиль снова виден.')} disabled={busy} aria-label={reader.public_visible ? 'Скрыть профиль' : 'Показать профиль'}>{reader.public_visible ? <EyeOff size={15} /> : <Eye size={15} />}</button><button type="button" onClick={() => { const delta=window.prompt('Изменение XP, например 20 или -20'); const reason=delta && window.prompt('Причина изменения'); if(delta&&reason) act({ action:'adjust-xp', publicId:reader.public_id, delta:Number(delta), reason },'XP исправлен, запись аудита сохранена.'); }} disabled={busy}>± XP</button><button type="button" onClick={() => { const code=window.prompt('Код совместного чтения, например september-dark-romance'); if(code) act({ action:'group-read', publicId:reader.public_id, eventKey:code },'Участие в совместном чтении учтено.'); }} disabled={busy}>+ Чтение</button><button type="button" onClick={() => { const title=window.prompt('Название специальной награды'); if(title) act({ action:'award', publicId:reader.public_id, nominationKey:`special-${Date.now()}`, title },'Награда назначена.'); }} disabled={busy}><Award size={15} /> Награда</button></article>)}</div></section>
    {data.adjustments?.length ? <section className="admin-level-card"><div><h2>Журнал изменений XP</h2><p>Ручные исправления и официальные совместные чтения.</p></div><div className="admin-xp-audit">{data.adjustments.map((item,index) => <article key={`${item.public_id}:${item.created_at}:${index}`}><span><strong>{item.display_name || item.public_id}</strong><small>{item.reason}</small></span><b>{item.old_xp} → {item.new_xp} XP</b><small>{item.changed_by} · {new Date(item.created_at).toLocaleString('ru-RU')}</small></article>)}</div></section> : null}
  </section>;
}
